### ISSUE TITLE
FHIR Connector resource operations error

### ISSUE THREAD

**Issue by marcses** [wso2-extensions/esb-connector-fhir#8]
I'm trying the FHIR Connector with WSO2 EI 6.1.0. I have tried some operations, but all return an error: 
```
Axis2Sender Unexpected error during sending message out
java.lang.NullPointerException...
```
I guess due to _The resource cannot be found_ in the response.

Follows the test of the `fhir.readSpecificResourceById`

My proxy is 
[proxy_fhir.txt](https://github.com/wso2-extensions/esb-connector-fhir/files/989155/proxy_fhir.txt)

My request is:
```
{
  "base": "https://sqlonfhir-stu3.azurewebsites.net",
  "type": "Patient",
  "format": "json",
  "id" : "3672b74bbde34e86a2cbcf9f1df8315c",
  "summary" : "true"
}
```
The log is:
[log_fhirConnector_readById.txt](https://github.com/wso2-extensions/esb-connector-fhir/files/989161/log_fhirConnector_readById.txt)

If I call directly the server fhir I have a correct response:
![directcall](https://cloud.githubusercontent.com/assets/26251486/25889834/83d6c02e-356b-11e7-9e46-2f87de88bedc.PNG)

**Comment by kesavany** [comment]
Hi Marcses,

Please try with the following request.

{
  "base": "https://sqlonfhir-stu3.azurewebsites.net/fhir",
  "type": "Patient",
  "id" : "3672b74bbde34e86a2cbcf9f1df8315c"
}

Thanks
Kesavan

**Comment by marcses** [comment]
Thanks,
this resolve the previous problem! Unfortunately, after i have this error: `RelayUtils Error while building Passthrough stream`
[log_fhirConnector_readById_2.txt](https://github.com/wso2-extensions/esb-connector-fhir/files/989735/log_fhirConnector_readById_2.txt)

**Comment by marcses** [comment]
I have posted other error in new issue
